# Generated by Django 5.2.4 on 2025-07-28 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the reservation')),
                ('hour_going', models.TimeField(blank=True, help_text='Departure time from the office', null=True)),
                ('hour_return', models.TimeField(blank=True, help_text='Return time from the restaurant', null=True)),
                ('reservation_type', models.CharField(choices=[('GOING', 'Only Going'), ('RETURN', 'Only Return'), ('BOTH', 'Going and Return')], default='BOTH', help_text='Type of reservation: only going, only return, or both', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of reservation creation')),
                ('user', models.ForeignKey(help_text='User who made the reservation', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
